
   
linters:
  enable:
  - depguard
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - gosimple
  - govet
  - ineffassign
  - lll
  - megacheck
  - revive
  - staticcheck
  - typecheck
  - unconvert
  - unused
 
  disable:
  - errcheck
  - goimports
linters-settings:
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/nil-labs/sdb
  govet:
    # enable or disable analyzers by name
    disable:
    - shadow
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
    - github.com/satori/go.uuid
    - github.com/satori/uuid
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 140
    # tab width in spaces. Default to 1.
    tab-width: 2